"""Initial migration

Revision ID: b8c4865d1b07
Revises: 
Create Date: 2025-05-13 01:54:52.518781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8c4865d1b07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gdadc_booking',
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('birthday', sa.String(length=50), nullable=False),
    sa.Column('document', sa.String(length=50), nullable=False),
    sa.Column('departure_date', sa.String(length=50), nullable=False),
    sa.Column('departure_iata', sa.String(length=50), nullable=False),
    sa.Column('arrival_iata', sa.String(length=50), nullable=False),
    sa.Column('arrival_date', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gdadc_booking')
    # ### end Alembic commands ###
